"""RegionalDisputeGenerator: the core reporter engine.

Renders formal dispute letters whose legal framing adapts to the jurisdiction on
the AuditContext: header, statutory references, cure period, and reservation-of-
rights clauses are pulled from config/legal/jurisdictions.yaml at render time.
Unknown jurisdictions fall back to DEFAULT (logged, never fatal). Every letter
embeds a counsel-review disclaimer — the engine drafts, licensed counsel signs off.
"""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, TemplateError
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from config.models import AuditResult, ErrorModel, Severity
from config.tolerances import UseCaseProfile

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).parent / "templates"
JURISDICTIONS_PATH = (
    Path(__file__).parent.parent / "config" / "legal" / "jurisdictions.yaml"
)
COUNSEL_DISCLAIMER = (
    "This letter was generated by an automated audit engine using exact decimal "
    "arithmetic against the source documents. The legal language herein is general "
    "in nature and should be reviewed by licensed counsel in the applicable "
    "jurisdiction before service."
)


class JurisdictionLegalProfile(BaseModel):
    """Legal framing for one jurisdiction, loaded from jurisdictions.yaml."""

    model_config = ConfigDict(strict=False, frozen=True)

    code: str
    display_name: str
    legal_header: str
    statutory_reference: str
    cure_period_days: int
    reservation_clauses: list[str] = Field(default_factory=list)
    counsel_disclaimer: str = COUNSEL_DISCLAIMER


class LegalClauseRegistry:
    """Loads jurisdiction language once; resolves codes with a DEFAULT fallback."""

    def __init__(self, path: Path = JURISDICTIONS_PATH) -> None:
        self._profiles: dict[str, JurisdictionLegalProfile] = {}
        self._load_error: ErrorModel | None = None
        try:
            raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            for code, block in raw.items():
                self._profiles[code.upper()] = JurisdictionLegalProfile.model_validate(
                    {"code": code.upper(), **block}
                )
        except (yaml.YAMLError, ValidationError, OSError) as exc:
            self._load_error = ErrorModel(
                module="reporter.generator",
                operation="load_jurisdictions",
                message=f"Failed to load jurisdiction language from {path}",
                detail=f"{type(exc).__name__}: {exc}",
            ).log()

    @property
    def load_error(self) -> ErrorModel | None:
        return self._load_error

    def available(self) -> list[str]:
        return sorted(self._profiles)

    def resolve(self, jurisdiction: str) -> JurisdictionLegalProfile | ErrorModel:
        code = (jurisdiction or "DEFAULT").strip().upper()
        if code in self._profiles:
            return self._profiles[code]
        if "DEFAULT" in self._profiles:
            logger.warning(
                "No legal profile for jurisdiction '%s'; falling back to DEFAULT", code
            )
            return self._profiles["DEFAULT"]
        return (
            self._load_error
            or ErrorModel(
                module="reporter.generator",
                operation="resolve",
                message=f"No legal profile for '{code}' and no DEFAULT available",
                detail=f"Known jurisdictions: {', '.join(self.available()) or 'none'}",
            ).log()
        )


class RegionalDisputeGenerator:
    def __init__(
        self,
        profile: UseCaseProfile,
        output_dir: Path,
        registry: LegalClauseRegistry | None = None,
    ) -> None:
        self.profile = profile
        self.output_dir = output_dir
        self.registry = registry or LegalClauseRegistry()
        self._env = Environment(
            loader=FileSystemLoader(TEMPLATE_DIR),
            autoescape=False,  # noqa: S701 — output is Markdown, not HTML
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate(
        self, result: AuditResult, jurisdiction: str = "DEFAULT"
    ) -> Path | None | ErrorModel:
        """Render the dispute letter. Returns None when there is nothing to dispute."""
        disputes = [f for f in result.findings if f.severity == Severity.DISPUTE]
        if not disputes and not result.unmatched_invoice_items:
            logger.info(
                "No dispute-grade findings for audit %s; no letter needed",
                result.audit_id,
            )
            return None

        legal = self.registry.resolve(jurisdiction)
        if isinstance(legal, ErrorModel):
            return legal

        try:
            template = self._env.get_template(self.profile.dispute_template)
            rendered = template.render(
                today=date.today().isoformat(),
                profile=self.profile,
                result=result,
                findings=disputes,
                unmatched_invoice=result.unmatched_invoice_items,
                legal=legal,
                audit_trail=result.audit_trail,
            )
            self.output_dir.mkdir(parents=True, exist_ok=True)
            out_path = self.output_dir / f"dispute_{result.audit_id}.md"
            out_path.write_text(rendered, encoding="utf-8")
            logger.info(
                "Dispute letter (%s) written to %s", legal.display_name, out_path
            )
            return out_path
        except (TemplateError, OSError) as exc:
            return ErrorModel(
                module="reporter.generator",
                operation="generate",
                message="Failed to generate dispute letter",
                detail=f"{type(exc).__name__}: {exc}",
            ).log()
